### ISSUE TITLE
Upgrades to CRS 4.0

### ISSUE THREAD

**Issue by jcchavezs** [corazawaf/coraza-coreruleset#10]
CRS 4.0 is out we should upgrade it and tag it here. I wonder if we should follow CRS versioning and add a suffix in case of further changes e.g. `4.0.0-coraza.1`

cc @anuraaga @M4tteoP @jptosso @fzipi

**Comment by fzipi** [comment]
That naming sounds natural to me.

**Comment by fzipi** [comment]
What will happen with.. plugins?
